### ISSUE TITLE
i cant find the way to ddpg

### ISSUE THREAD

**Issue by Uncle-Justice** [itrummer/dbbert#5]
hi, I greatly admire the work you have done. i saw you have some experiment about ddpg in your dbbert paper. i wanna try this through your code, but i cant find your implementation about ddpg.

For example, i try to run `run_ddpg.py`. It reports `analysis.simulation` not found. Then i didnt find any implementation about 'simulation' in the code.

Is it some package that needs to be imported?  

Looking forward to your reply, I will be very grateful.

**Comment by itrummer** [comment]
Hi, 
Sorry for the late reply! 
DDPG is implemented here: https://github.com/cmu-db/ottertune 
You need to include the code in your path.
Cheers
